-- DEPRECATED
-- The original client-trusted create_order signature has been retired.
-- Apply sql/menu_production_hardening.sql instead.
-- The hardened RPC validates restaurant/branch/product/options/coupon state and
-- calculates subtotal, VAT, delivery fee, discount and total inside PostgreSQL.
